import 'package:get/get.dart';
import 'package:hiring_task_1/model/user_model.dart';

class UserbaseController extends GetxController {
  Autogenerated autogenerated = Autogenerated();
  static updateUpdateUser(Autogenerated user) {
    final controller = Get.put(UserbaseController(), permanent: true);
    controller.autogenerated = user;
    controller.update();
  }

  static Data get userData {
    return Get.put(UserbaseController(), permanent: true).autogenerated.data!;
  }
}
